from .registry import EffectRegistry
from .deepdream import DeepDreamEffect
from .edge_glow import EdgeGlowEffect
from .color_grade import ColorGradeEffect
from .style_transfer import StyleTransferEffect
from .depth_blur import DepthBlurEffect
from .morphology_effect import MorphologyEffect
from .temporal import TemporalBlender
from .audio_reactive import AudioReactiveEngine
from .segmentation import SegmentationEffect
from .super_resolution import SuperResEffect
from .glitch import GlitchEffect
from .warp import WarpEffect
from .halftone import HalftoneEffect
from .dreamwave import DreamWaveEffect
